src/blog/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from accounts.views import (login_view, register_view, logout_view)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^comments/', include("comments.urls", namespace='comments')),
    url(r'^register/', register_view, name='register'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^', include("posts.urls", namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	)

urlpatterns = [
	url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name="detail"),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete, name="delete"),
    #url(r'^posts/$', "<appname>.views.<function_name>"),
]

src/comments/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse


from django.db import models

# Create your models here.

class CommentManager(models.Manager):
	def all(self):
		qs = super(CommentManager, self).filter(parent=None)
		return qs
		
	def filter_by_instance(self, instance):
		content_type = ContentType.objects.get_for_model(instance.__class__)
		obj_id = instance.id
		qs = super(CommentManager, self).filter(content_type=content_type, object_id=obj_id).filter(parent=None)
		return qs

class Comment(models.Model):
	user 		= models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
	
	content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True)
	object_id = models.PositiveIntegerField(null=True)
	content_object = GenericForeignKey('content_type', 'object_id')
	parent         = models.ForeignKey("self", null=True, blank=True)

	content 	= models.TextField()
	timestamp 	= models.DateTimeField(auto_now_add=True)

	objects = CommentManager()

	def get_absolute_url(self):
		return reverse("comments:thread", kwargs={"id": self.id})


	def get_delete_url(self):
		return reverse("comments:delete", kwargs={"id": self.id})

	class Meta:
		ordering = ['-timestamp']

	def __unicode__(self):
		return str(self.user.username)

	def __str__(self):
		return str(self.user.username)	

	def children(self): # replies
 		return Comment.objects.filter(parent=self)

	@property
	def is_parent(self):
		if self.parent is not None:
			return False
		return True	

src/posts/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify

from markdown_deux import markdown
import urllib

from comments.models import Comment
from .utils import get_read_time

# Create your models here.
# MVC MODEL VIEW CONTROLLER


#Post.objects.all()
#Post.objects.create(user=user, title="Some time")
class PostManager(models.Manager):
	def active(self, *args, **kwargs):
		##Post.objects.all() = super(PostManager, self).all()
		return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())

def upload_location(instance, filename):
	return "%s/%s" %(instance.id, filename)

class Post(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
	title = models.CharField(max_length=120) 
	slug = models.SlugField(unique=True)
	image = models.ImageField(upload_to=upload_location,
							  null=True, 
							  blank=True, 
							  height_field="height_field", 
							  width_field="width_field")
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	draft = models.BooleanField(default=False)
	publish = models.DateField(auto_now=False, auto_now_add=False)
	read_time = models.IntegerField(default=0) #models.TimeField(null=True, blank=True)
	content = models.TextField()
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

	def __unicode__(self):
		return self.title

	def __str__(self):
		return	self.title

	objects = PostManager()	

	def get_absolute_url(self):
		return reverse("posts:detail", kwargs={"slug": self.slug})
		#return "/posts/%s/" %(self.id)	

	class Meta:
		ordering = ["-timestamp", "-updated"]	

	def get_markdown(self):
		content = self.content
		markdown_text = markdown(content)
		if "http" in markdown_text:
			markdown_text = markdown_duex_url_decoder(markdown_text)
		return mark_safe(markdown_text)

	@property
	def comments(self):
		instance = self
		qs = Comment.objects.filter_by_instance(instance)
		return qs	

	@property
	def get_content_type(self):
		instance = self
		content_type = ContentType.objects.get_for_model(instance.__class__)
		return content_type

def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
    	html_string = instance.get_markdown()
    	read_time_var = get_read_time(html_string)
    	instance.read_time = read_time_var    

def markdown_duex_url_decoder(markdown_text):
	markdown_text_list = markdown_text.split("\"")
	encoded_url = markdown_text_list[1]
	decoded_url = urllib.unquote(encoded_url).decode('utf8')
	markdown_text_list[1] = decoded_url
	return "\"".join(markdown_text_list)


pre_save.connect(pre_save_post_receiver, sender=Post)

src/posts/forms.py
from django import forms

from pagedown.widgets import PagedownWidget

from .models import Post

class PostForm(forms.ModelForm):
	content = forms.CharField(widget=PagedownWidget(show_preview=False))
	publish = forms.DateField(widget=forms.SelectDateWidget)
	class Meta:
		model = Post
		fields = [
			"title",
			"content",
			"image",
			"draft",
			"publish",
		]

src/posts/views.py
from urllib import quote_plus

from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone
from django.db.models import Q

from comments.models import Comment
from comments.forms import CommentForm
from .forms import PostForm
from .models import Post




def post_list(request): #list items
	today = timezone.now().date()
	queryset_list = Post.objects.active() #.order_by('-timestamp')
	if request.user.is_staff or request.user.is_superuser:
		queryset_list = Post.objects.all()

	query = request.GET.get("q")
	if query:
		queryset_list = queryset_list.filter(
						Q(title__icontains=query)|
						Q(content__icontains=query)|
						Q(user__first_name__icontains=query)|
						Q(user__last_name__icontains=query)
						).distinct()	
	paginator = Paginator(queryset_list, 3) # Show 25 contacts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)

	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)

	context = {
	"object_lists": queryset,
	"title": "List",
	"page_request_var": page_request_var,
	"today": today,
	}
	return render(request, "post_list.html", context)


def post_create(request):
	username = str(request.user)
	user = User.objects.filter(username=username)
	if user.count() != 1:
		raise Http404
	form = PostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.user = request.user
		instance.save()
		messages.success(request, "Successfully Created")
		return HttpResponseRedirect(instance.get_absolute_url())
		
	context = {
		"form": form,
	}
	return render(request, "post_form.html", context)


def post_detail(request, slug=None): #retrieve
	instance = get_object_or_404(Post, slug=slug)
	if instance.publish > timezone.now().date() or instance.draft:
		if not request.user.is_staff or not request.user.is_superuser:
			raise Http404
	share_string = quote_plus(instance.content)
	
	initial_data = {
		"content_type": instance.get_content_type,
		"object_id": instance.id,
	}

	form = CommentForm(request.POST or None, initial=initial_data)
	if form.is_valid() and request.user.is_authenticated():
		c_type = form.cleaned_data.get("content_type")
		content_type = ContentType.objects.get(model=c_type)
		obj_id = form.cleaned_data.get("object_id")
		content_data = form.cleaned_data.get("content")
		parent_obj = None
		try:
			parent_id = int(request.POST.get("parent_id"))
		except:
			parent_id = None

		if parent_id:
			parent_qs = Comment.objects.filter(id=parent_id)
			if parent_qs.exists() and parent_qs.count() == 1:
				parent_obj = parent_qs.first()


		new_comment, created = Comment.objects.get_or_create(
										user = request.user,
										content_type = content_type,
										object_id = obj_id,
										content = content_data,
										parent = parent_obj,
								)
		return HttpResponseRedirect(new_comment.content_object.get_absolute_url())

	comments = instance.comments #Comment.objects.filter_by_instance(instance)
	context = {
		"title": instance.title,
		"instance": instance,
		"share_string": share_string,
		"comments": comments,
		"comment_form": form,
	}
	return render(request, "post_detail.html", context)


def post_update(request, slug=None):
	instance = get_object_or_404(Post, slug=slug)
	
	if request.user.is_staff or request.user.is_superuser:
		pass
	elif request.user != instance.user:
		raise Http404	
	
	form = PostForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		messages.success(request, "<a href='#'>Item </a> Saved", extra_tags='html_safe')
		return HttpResponseRedirect(instance.get_absolute_url())

	context = {
		"title": instance.title,
		"instance": instance,
		"form": form,
	}	
	return render(request, "post_form.html", context)


def post_delete(request, slug=None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	instance = get_object_or_404(Post, slug=slug)
	instance.delete()
	messages.success(request, "Successfully Deleted")
	return redirect("posts:list")

src/templates/base.html
{% load staticfiles %}
<!--DOCTYPE html -->
<html>
<head>
<title>{% block head_title %}Django Blog 1.9{% endblock head_title %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<link rel='stylesheet' href='{% static "css/base.css" %}' />

{% block head_extra %} {% endblock head_extra %}
</head>

<body>

	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>

	{% include "messages_display.html" %}
	<div class='container'>
		<ol class='breadcrumb'>
			<li><a href='{% url "posts:list" %}'>Home</a></li>
			{% block post_detial_link %}
			{% endblock %}

			{% if not request.user.is_authenticated %}
			<li class='pull-right'><a href='{% url "register"%}'>Register</a></li>
			<li class='pull-right'><a href='{% url "login"%}'>Login</a></li>
			{% else %}

			<li class='pull-right'><a href='{% url "logout"%}'>Logout</a></li>
				{% block post_create_link %}
				{% endblock %}
				{% block post_update_link %}
				{% endblock %}
				{% block post_delete_link %}
				{% endblock %}
			{% endif %}

		</ol>

		{% block content %}

		{% endblock content %}
	</div>

<!-- Latest compiled and minified JavaScript -->
<script src="http://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
crossorigin="anonymous"></script>

<script scriptrc="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	$(".content-markdown").each(function(){
		var content = $(this).text()
		var markedContent = marked(content)
		$(this).html(markedContent)
	})

	$(".post-detail-item img ").each(function(){
		$(this).addClass('img-responsive')
	})

	var titleInput = $("#id_title")

	function setTitle(value){
		$("#preview-title").text(value)
	}
	setTitle(titleInput.val())

	titleInput.keyup(function(){
		var newTitle = $(this).val()
		setTitle(newTitle)
	})

	var contentInput = $("#id_content")

	function setContent(value){
		var markedContent = marked(value)
		$("#preview-content").html(markedContent)
		$("#preview-content img").each(function(){
			$(this).addClass("img img-responsive")
		})
	}
	setContent(contentInput.val())

	contentInput.keyup(function(){
		var newContent = $(this).val()
		setContent(newContent)
	})

	$(".comment-reply-btn").click(function(event){
		event.preventDefault();
		$(this).parent().next(".comment-reply").fadeToggle();
	})

	
})
</script>
</body>
</html>

src/templates/comment_thread.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% load urlify %}

{% block head_title %}
	
	{{ comment.content_object.title }} | {{ block.super }}

{% endblock head_title %}



{% block post_detial_link %}
	<li><a href="{{ comment.content_object.get_absolute_url }}">{{ comment.content_object.title }}</a></li>
{% endblock %}


{% block content %}
	<div class='col-sm-8 col-sm-offset-2'>
	  				<p class="mb-0">{{ comment.content }}</p>
	  				<footer>via {{ comment.user }} | {{ comment.timestamp|timesince }} ago {% if comment.children.count > 0 %} |
	  				{{ comment.children.count }} Comment{% if comment.children.count > 1 %}s {% endif %}{% endif %} | 
	  				{% if request.user == comment.user %}<a href="{{ comment.get_delete_url }}"> Delete </a>{% endif %}</footer>
	  			    <hr/> 
	  				{% for child_comment in comment.children %}
		  				<blockquote class="blockquote">
			  				<p class="mb-0">{{ child_comment.content }}</p>
			  				<footer>via {{ child_comment.user }} | {{ child_comment.timestamp|timesince }} ago | 
			  				{% if request.user == comment.user %}<a href="{{ child_comment.get_delete_url }}"> Delete </a>{% endif %}</footer>
						</blockquote>		
						<hr/>
					{% endfor %}
					{% if request.user.is_authenticated %}
					<form method='POST' action=".">{% csrf_token %}
						{{ form|crispy }}
						<input type='hidden' name='parent_id' value='{{ comment.id }}'>
						<input type='submit' value='Reply' class='btn btn-default'>
					</form>
					{% else %}
					<p> You must login to comment </p>
					{% endif %}
				<hr/>
	</div>

{% endblock content %}

src/templates/confirm_delete.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% load urlify %}

{% block head_title %}
	
	{{ instance.title }} | {{ block.super }}

{% endblock head_title %}


{% block content %}
	<div class='col-sm-8 col-sm-offset-2'>
	  	<h1>Confrim Delete :</h1>
	  	<hr/>
		<form method='POST' action=".">{% csrf_token %}
			<p>Are sure want to Delete : "{{ object.content }}" ?</p>
			<input type='submit' value='Confrim' class='btn btn-warning'>
			<a href="{{ object.content_object.get_absolute_url }}" class='btn btn-default'> Cancle </a>
		</form>
		<hr/>
	</div>

{% endblock content %}

src/templates/form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block head_extra %} 
	
	{{ form.media }}

{% endblock head_extra %}

{% block content %}

<div class='col-sm-4 col-sm-offset-4'>
	<h1> {{ title }} </h1>
	<hr/>
	<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}	
		{{ form|crispy }}
		<input type='submit' class='btn btn-default' value='{{ title }}' />
	</form>
</div>

{% endblock content %}

src/templates/messages_display.html
 {% if messages %}
    <div class='messages'>

    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    </ul>

    </div>
{% endif %}

src/templates/post_detail.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% load urlify %}

{% block head_title %}
	
	{{ instance.title }} | {{ block.super }}

{% endblock head_title %}

{% block post_detial_link %}
	<li><a class="nav-link" href="{{ isntance.get_absolute_url }}">{{ instance.title }}</a></li>
{% endblock %}

{% block post_update_link %}
	<li class='pull-right'><a href='{{ instance.get_absolute_url}}edit'>Edit</a></li>
{% endblock %}
{% block post_delete_link %}
	<li class='pull-right'><a href='{{ instance.get_absolute_url}}delete'>Delete</a></li>
{% endblock %}

{% block content %}
	<div class='col-sm-8 col-sm-offset-2'>
		{% if instance.image %}
		<img src='{{ instance.image.url }}' class='img-responsive'/>
		{% endif %}
		<h1> {{ title }} <small>{% if instance.draft %}<span style='color:red;'> Draft </span>{% endif %}{{ instance.publish }} </small></h1>

		<!-- using template tags -->
	    <!-- <p>Read Time : {% if instance.read_time|time:"i" <= "01" %} < 1 minute {% else %} {{ instance.read_time | time:" i " }} minutes {% endif %}</p> -->

	    <p> Read Time : {% if instance.read_time <= 1 %} < 1 minute {% else %} {{ instance.Read_time }} minutes {% endif %}</p>
		{% if instance.user.get_full_name %}
		<p>Author: {{ instance.user.get_full_name }}</p>
		{% endif %}
		<p>
			<div class="fb-like" data-href="{{ request.build_absolute_uri }}"z data-layout="button_count" data-action="like" data-size="large" data-show-faces="true" data-share="true"></div>
		</p>

		<p>
			<a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
			Facebook
			</a>
			|
			<a href="https://twitter.com/home?status={{ instance.content|truncatechars:80|urlify }}%20{{ request.build_absolute_uri }}">
			Twitter
			</a>
			|
			<a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}'>
			Google Plus
			</a>
			|
			<a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{ instance.title }}&summary={{ share_string }}&source={{ request.build_absolute_uri }}">
			Linkedin
			</a> 
			|
			<a href="http://www.reddit.com/submit?url={{ request.build_absolute_uri }}&title={{ share_string }}">
			Reddit
			</a>
		</p>
		<hr/>
		<div class='row'>
		<div class='col-sm-12 '>

		<div class='post-detail-item'> {{ instance.get_markdown }} </div>

		<hr/>
		<br/>
		<div>
			<p class="lead">Comments :</p>
			{% if request.user.is_authenticated %}
			<form method='POST' action=".">{% csrf_token %}
				{{ comment_form|crispy }}
				<input type='submit' value='Post Comment' class='btn btn-default'>
			</form>
			{% else %}
			<p> You must login to comment </p>
			{% endif %}
			{% for comment in comments %}
				<blockquote class="blockquote">
	  				<p class="mb-0">{{ comment.content }}</p>
	  				<footer>via {{ comment.user }} | {{ comment.timestamp|timesince }} ago {% if comment.children.count > 0 %} |
	  				{{ comment.children.count }} Comment{% if comment.children.count > 1 %}s {% endif %}{% endif %} {% if request.user.is_authenticated %}<a class="comment-reply-btn" href="#">| Reply </a>{% endif %} | <a class="" href="{{ comment.get_absolute_url }}"> Thread </a></footer> 
	  				<div class="comment-reply" style='display:none;'>
		  				{% for child_comment in comment.children %}
			  				<blockquote class="blockquote">
				  				<p class="mb-0">{{ child_comment.content }}</p>
				  				<footer>via {{ child_comment.user }} | {{ child_comment.timestamp|timesince }} ago</footer>
							</blockquote>		
							<hr/>
						{% endfor %}
						{% if request.user.is_authenticated %}
						<form method='POST' action=".">{% csrf_token %}
							{{ comment_form|crispy }}
							<input type='hidden' name='parent_id' value='{{ comment.id }}'>
							<input type='submit' value='Reply' class='btn btn-default'>
						</form>
						{% else %}
						<p> You must login to comment </p>
						{% endif %}
					</div>	
				</blockquote>
				<hr/>

			{% endfor %}	
		</div>		

		<!-- {{ instance.comment_set.all }} -->
		<!-- <div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5"></div> -->
		</div>
		</div>
	</div>

{% endblock content %}

src/templates/post_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block head_extra %} 
	
	{{ form.media }}

{% endblock head_extra %}

{% block post_detial_link %}
	<li><a class="nav-link" href="{{ isntance.get_absolute_url }}">{{ instance.title }}</a></li>
{% endblock %}

{% block content %}

<div class='col-sm-3 '>	
	<h1> From </h1>
	<hr/>
	<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}	
		{{ form|crispy }}
		<input type='submit' class='btn btn-default' value='create post' />
	</form>
</div>
<div class='col-sm-6 col-sm-offset-3'>
	<h1>Preview</h1>
	<hr/>
	<div class='content-preview'>
		<h3 id='preview-title'></h3>
		<hr/>
		<p id='preview-content'></p>
	</div>
</div>

{% endblock content %}

src/templates/post_list.html
{% extends "base.html" %}

{% block post_create_link %}
	<li class='pull-right'><a href='{% url "posts:create"%}'>Post</a></li>
{% endblock %}

{% block content %}

	<div class='col-sm-8 col-sm-offset-2'>
		<form method='GET' action='' class='row'>
			<div class='col-sm-6'>
				<div class='input-group'>
					<input class='form-control' type='text' name='q' placeholder='Search posts' value='{{ request.GET.q }}'/>
					<span class='input-group-btn'>
						<!-- <input class='btn btn-default' type='submit' value='Search' /> -->
						<button class='btn btn-defalut' type='submit'><i class="fa fa-search" aria-hidden="true"></i> Search</button>
					</span>
				</div>
			</div>
		</form>
		{% for obj in object_lists %}
			<div class="row">
				<div class="col-sm-12">
					<div class="thumbnail">
					{% if obj.image %}
					  <img src='{{ obj.image.url }}' class='img-responsive'/>
					{% endif %}  	
					  <div class="caption post-detail-item">
					  	{% if obj.draft %}<h3>Staff Only: Draft</h3>{% endif %} {% if obj.publish > today %}<h3>Staff Only: Futre Post</h3>{% endif %}
					    <h3><a href='{{ obj.get_absolute_url }}'>{{ obj.title }}</a>   <small>{{ obj.publish }} </small></h3>
					    {% if obj.user.get_full_name %}
						<p>Author: {{ obj.user.get_full_name }}</p>
						{% endif %}
					    {{ obj.get_markdown|truncatechars_html:20 }}
					    <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">View</a></p>
					  </div>
					</div>	
				</div>
				<hr/>
			</div>			
			<!-- {% cycle "" "<div class='col-sm-12'><hr/></div></div><div class='row'>" %} -->
		{% endfor %}		

		<div class="pagination">
		    <span class="step-links">
		        {% if object_lists.has_previous %}
		            <a href="?{{ page_request_var }}={{ object_lists.previous_page_number }}&{% if request.GET.q %}q={{ request.GET.q }}{% endif %}">previous</a>
		        {% endif %}

		        <span class="current">
		            Page {{ object_lists.number }} of {{ object_lists.paginator.num_pages }}.
		        </span>

		        {% if object_lists.has_next %}
		            <a href="?{{ page_request_var }}={{ object_lists.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
		        {% endif %}
		    </span>
		</div>
	</div> 

{% endblock content %}